# Generated by Django 5.1 on 2024-10-31 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Mempool", "Mempool Node"),
                            ("Miner", "Miner Node"),
                            ("Storage", "Storage Node"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("t_hash", models.CharField(max_length=64)),
                ("n", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("druid_info", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TxOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=8, max_digits=20)),
                ("locktime", models.PositiveBigIntegerField()),
                (
                    "drs_block_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "script_public_key",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                (
                    "node_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blockchain.nodetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DruidDroplet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("druid", models.CharField(max_length=64, unique=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blockchain.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_hash", models.CharField(max_length=64)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("proof_of_work", models.CharField(max_length=64)),
                (
                    "mined_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("transactions", models.ManyToManyField(to="blockchain.transaction")),
            ],
        ),
        migrations.CreateModel(
            name="TxIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("script_signature", models.TextField()),
                (
                    "previous_out",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blockchain.outpoint",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="inputs",
            field=models.ManyToManyField(to="blockchain.txin"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="outputs",
            field=models.ManyToManyField(to="blockchain.txout"),
        ),
    ]
